### ISSUE TITLE
Split r3.hpp into multiple files?

### ISSUE THREAD

**Issue by yupinghuang** [Radio-Camera-Initiative/r3_central_manager#19]
hide some implementation etc.

**Comment by mlaures** [comment]
Templated classes cannot have implementations hidden, but there are some changes that could be made to split up r3.hpp

1. reuseable_buffer and buffer_ptr could exist in their own file, and recycle_memory could be in another.
2. reuseable_buffer could be hidden from the r3.hpp, and keep buffer_ptr and recycle_memory (which users can use) together. Main drawback here is the `->` operator as users can't see what variables can be directly accessed from the buffer_ptr

**Comment by yupinghuang** [comment]
1 sounds better to me

**Comment by yupinghuang** [comment]
Neat!
